from dotenv import load_dotenv
import os
load_dotenv()

RABBITMQ_INGESTION_EXCHANGE=os.environ["RABBITMQ_INGESTION_EXCHANGE"]
RABBITMQ_INGESTION_QUEUE=os.environ["RABBITMQ_INGESTION_QUEUE"]
RABBITMQ_INGESTION_KEY=os.environ["RABBITMQ_INGESTION_KEY"]
RABBITMQ_URI=os.environ["RABBITMQ_URI"]
MONGO_URI = os.environ["MONGO_URI"]
ENV = os.environ["ENV"]